import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import Sidebar from '@/components/Sidebar';
import {Categories,Feed,Pagination,PostMeta} from '@/components/Posts';
import {archiveRoutes,articles,articleFor,imageFor,renderedBody,routeFor,site,type Article} from '@/lib/content';
export const dynamicParams=false;
export function generateStaticParams(){return archiveRoutes.map(r=>({segments:r.path.split('/').filter(Boolean)}));}
type Props={params:Promise<{segments:string[]}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {segments}=await params;const route=routeFor('/'+segments.join('/')+'/');if(!route)return {};const article=route.article;const image=imageFor(article?.featuredImage)?.localPath;return {title:route.title,description:article?.excerpt||`${route.title} kategorisindeki FuturistikZone yazıları.`,alternates:{canonical:route.path},openGraph:{title:route.title,description:article?.excerpt,type:route.kind==='article'?'article':'website',url:route.path,images:image?[{url:image}]:[],...(route.kind==='article'&&article?.publishedAt?{publishedTime:article.publishedAt,authors:article.author?[`https://futuristikzone.com${article.author.path}`]:[]}: {})},twitter:{card:'summary_large_image',title:route.title,images:image?[image]:[]}};}
function Contact(){const enabled=process.env.NEXT_PUBLIC_CONTACT_FORM_ENABLED==='true';return <section className="contact-form-section">{enabled?<form name="contact" method="POST" action="/tesekkurler/" data-netlify="true" data-netlify-honeypot="bot-field"><input type="hidden" name="form-name" value="contact"/><p hidden><label>Bu alanı boş bırakın<input name="bot-field"/></label></p><label>Adınız<input name="name" autoComplete="name" required/></label><label>E-posta adresiniz<input name="email" type="email" autoComplete="email" required/></label><label>Konu<input name="subject" required/></label><label>Mesajınız<textarea name="message" rows={7} required/></label><button>Gönder</button></form>:<p>Mesaj formu henüz kullanıma açık değil. <a href={site.socials.find(s=>s.name==='Instagram')?.url||site.socials[0].url}>Bize sosyal hesabımızdan ulaşabilirsiniz.</a></p>}</section>;}
function ArticleContent({article}:{article:Article}){const image=imageFor(article.featuredImage);const related=articles.filter(p=>p.path!==article.path&&p.categories.some(c=>article.categories.some(t=>c.path===t.path))).slice(0,3);const older=article.previous&&articleFor(article.previous.path),newer=article.next&&articleFor(article.next.path);const avatar=imageFor(article.authorDetails?.image);return <>
  <Categories terms={article.categories}/><h1 className="article-title">{article.title}</h1><PostMeta post={article}/>
  {image?.localPath&&<img className="article-featured" src={image.localPath} width={image.width} height={image.height} alt={article.title}/>}
  <div className="article-body" dangerouslySetInnerHTML={{__html:renderedBody(article)}}/>
  {article.tags.length>0&&<nav className="post-tags" aria-label="Yazı etiketleri">{article.tags.map(t=><a key={t.path} href={t.path}>{t.name}</a>)}</nav>}
  {article.author&&<section className="author-box">{avatar?.localPath&&<img src={avatar.localPath} alt="" width="100" height="100" loading="lazy"/>}<div><h3><a href={article.author.path}>{article.author.name}</a></h3>{article.authorDetails?.bio&&<p>{article.authorDetails.bio}</p>}{article.authorDetails?.socials.length? <nav aria-label="Yazarın sosyal hesapları">{article.authorDetails.socials.map(url=><a key={url} href={url} rel="noopener noreferrer">{new URL(url).hostname.replace(/^www\./,'')}</a>)}</nav>:null}</div></section>}
  <nav className="adjacent-posts" aria-label="Diğer yazılar">{older&&<a href={older.path}><span>önceki yazı</span>{older.title}</a>}{newer&&<a href={newer.path}><span>sonraki yazı</span>{newer.title}</a>}</nav>
  {related.length>0&&<section className="related-posts"><h2>Related Posts</h2><div>{related.map(p=>{const image=imageFor(p.featuredImage);return <article key={p.path}>{image?.localPath&&<a href={p.path}><img src={image.localPath} alt="" loading="lazy"/></a>}<h3><a href={p.path}>{p.title}</a></h3></article>;})}</div></section>}
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'Article',headline:article.title,datePublished:article.publishedAt,author:article.author?{'@type':'Person',name:article.author.name,url:`https://futuristikzone.com${article.author.path}`}:undefined,mainEntityOfPage:`https://futuristikzone.com${article.path}`,image:image?.localPath?`https://futuristikzone.com${image.localPath}`:undefined,publisher:{'@type':'Organization',name:'FuturistikZone',url:'https://futuristikzone.com'}}).replace(/</g,'\\u003c')}}/>
  </>;}
export default async function ContentPage({params}:Props){const {segments}=await params;const route=routeFor('/'+segments.join('/')+'/');if(!route)notFound();const contact=route.path==='/iletisim/';return <div className={`site-columns container inner-page ${contact?'wide-page':''}`}><main id="main-content">
  {route.kind==='article'&&route.article?<ArticleContent article={route.article}/>:route.kind==='page'&&route.article?<><h1 className="page-title">{route.title}</h1><div className="article-body" dangerouslySetInnerHTML={{__html:renderedBody(route.article)}}/>{contact&&<Contact/>}</>:<><h1 className="archive-title">{route.title}</h1><Feed posts={route.posts||[]}/><Pagination base={route.base} current={route.page} pages={route.pages||[1]}/></>}
  </main>{!contact&&<Sidebar/>}</div>;}
